name: Code checks

on:
  push:
    branches:
      - '*'

jobs:
  code-checks:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '11'

      - name: Build
        run: mvn package
